### ISSUE TITLE
http proxy 默认是支持的吗

### ISSUE THREAD

**Issue by red3** [shadowcoel/ShadowCoel#6]
测试 http proxy 的时候，
1. 代码里面的 onHttpProxyCallback 回调成功的
2. 实际 rule match 里面报：Ignore. No Proxy Provided.

所以想问 http proxy 是默认支持的吗，看代码层面应该是支持到了，如果是需要改代码想请教下从哪个层面入手，多谢。

**Comment by TheWanderingCoel** [comment]
如果你的说的是本地的那个http proxy(privoxy)那个是有的,如果是代理添加的那个HTTP的话并没有完成。我也好久没动过这个项目了，主要就是加了一小点前端的东西。

**Comment by red3** [comment]
嗯，确实，看了下，本地的 http proxy 和 socks proxy 应该都是为 ss 提供服务的。默认启动的 proxy 是 ss ，目前看应该也是写死的。
